PODAAC-5173: Add OPeNDAP Tutorials on Cloud Set Up and Subsetting
podaac/tutorials pull request #97
Opened 2023-03-04 00:09 UTC by phoeberepo

This PR adds two tutorials outlining cloud set up and subsetting.

2023-03-07 19:57 UTC, cassienickles requested changes
Hey Phoebe, these tutorials look great! Love the step by step instructions! They're easy to follow & clear. In the beginning though of each, could you add a summary of what the notebook does and learning objectives of what the user would expect to learn from each? We've got a template here that you can look at for what we typically like to have in our tutorials: https://github.com/podaac/tutorials/blob/master/notebooks/Tutorials_TEMPLATE.ipynb
Your tutorial doesn't have to follow this format exactly, as long as the elements are stated in some fashion (like you have requirements already in your tutorials even if it doesn't call them out explicitly like the template which totally works.) Please also add your name as author!

Also, it would be helpful to have a bit more explanation in the credentials tutorial. For example, what does the .dodsrc  file do and why do I need it? Doesn't have to be long but would love a sentence of more info to help users along. Thanks!

2023-03-07 20:55 UTC, ScienceCat18 reviewed
Hi Phoebe, thanks for putting these together, they are great! A few comments for your consideration, most are to try to be consistent in how we present tutorials to end-users, and to integrate/leverage existing How-Tos:

**Setup notebook**

- are all steps 1-4 necessary, or as long as user has EDL and netrc set up, opendap call (in e.g. subsetting notebook) is expected to work? So, similar question to Cassie, what is .dodsrc for? and are the urs_cookies necessary (I haven't seen that before in other (PO)DAAC tutorials, is it specific to Cloud-OPeNDAP?)
- I ask because we're trying to have a more consistent and unified way for users to deal with EDL, following this 2021 Cloud Hackathon How-To, now part of our Cookbook: https://podaac.github.io/tutorials/external/NASA_Earthdata_Authentication.html. Would it make sense to include a short blurb on EDL in the Subsetting example - pointing to this EDL How-To i referenced, and reduce the need to have the Setup notebook as well? 
- the other pieces in the Setup notebook could then be relabel as troubleshooting Cloud-OPeNDAP, for example, as an optional helper notebook, not a mandatory one. What do you think?

**Subsetting notebook**

- could we update the Intro part per Cassie's comment, to follow the end-user tutorial template? e.g. include Authorship, Summary, any Compute Environment Requirements (i.e. can this be run locally or has to be in the Cloud, or both?), Learning Objectives, link to EDL to set up authentication, move imports to the beginning
- in Summary or Learning Objectives (per template): could we add a short blurb to say this notebook is a programmatic way of using Cloud-OPeNDAP, and for more ways to use the tool, see https://podaac.jpl.nasa.gov/OPeNDAP-in-the-Cloud (if that's still accurate, if not let's update that one as well). Just trying to tie all the tutorial pieces together, to keep it as simplified. and consistent for end-users as possible.

Thanks so much, this is exciting! And as a side note, through the NASA Earthdata Cloud Cookbook development through the NASA Openscapes, we have other DAAC colleagues developing an Opendap tutorial; will be interesting to see how much overlap there is in using cloud opendap across different DAACs, and if we need to make any further connections across these tutorials/systems/tools.

2023-03-07 23:06 UTC, cassienickles commented
Also another thing I thought of: Do we want to assume the user already knows how to find the OPeNDAP links or do we want to tell them how to find the link they desire in the most efficient way? Either way works but we should probably be explicit and if not show them how to find the link directly in the tutorial, point to where there are directions/where they could find it. Thanks!

2023-03-17 22:09 UTC, phoeberepo commented
@cassienickles @ScienceCat18 I applied your feedback above. Please see latest updates. 

@ScienceCat18 https://podaac.github.io/tutorials/external/NASA_Earthdata_Authentication.html -- this authentication tutorial does not provide OPeNDAP in the cloud API access so I do not recommend adding this to these tutorials.

2026-03-25 15:21 UTC, phoeberepo commented
Closing this PR as this is no longer applicable and obsolete.

2026-03-25 15:21 UTC, closed without merging